# Generated by Django 5.1.6 on 2025-03-01 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0002_pessoa_cep_pessoa_cidade_pessoa_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meuapp.pessoa')),
            ],
        ),
    ]
